## Initial Setup

In [1]:
#Initial imports

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats as st



## Reading Dataset 

In [2]:
#Loading dataset to python

df = pd.read_csv("D:\\Data Science and Analytics\\CaseStudy 10\\mushrooms.csv")
df.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

## Cleaning and preprocessing

In [3]:
df.shape

(8124, 23)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring  

In [5]:
df.describe()

class cap-shape cap-surface cap-color bruises  odor gill-attachment  \
count   8124      8124        8124      8124    8124  8124            8124   
unique     2         6           4        10       2     9               2   
top        e         x           y         n       f     n               f   
freq    4208      3656        3244      2284    4748  3528            7914   

       gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
count          8124      8124       8124  ...                     8124   
unique            2         2         12  ...                        4   
top               c         b          b  ...                        s   
freq           6812      5612       1728  ...                     4936   

       stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
count                    8124                   8124      8124       8124   
unique                      9                      9         1          4   
top                         w                      w         p          w   
freq                     4464                   4384      8124       7924   

       ring-number ring-type spore-print-color population habitat  
count         8124      8124              8124       8124    8124  
unique           3         5                 9          6       7  
top              o         p                 w          v       d  
freq          7488      3968              2388       4040    3148  

[4 rows x 23 columns]

In [6]:
#Checking null vales

df.isnull().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [7]:
#There are no null values

## Encoding 

In [8]:
from sklearn import preprocessing 
df.loc[:]=df.apply(preprocessing.LabelEncoder().fit_transform)

## Splitting into feature set and class variable

In [9]:
y=df["class"]
X=df.drop(['class'], axis = 1)

## Splitting to train and test set

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3,random_state=2)

# Probablistic Supervised Machine Learning models

## 1. Fitting Gaussian Naive Bayes to Training Set 

In [11]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train,y_train)

GaussianNB()

## Prediction of the test set result:

In [12]:
y_pred = classifier.predict(X_test)

## Checking confusion matrix and accuracy

In [13]:
from sklearn.metrics import confusion_matrix,accuracy_score

cm=confusion_matrix(y_test,y_pred)
print("The confucion matrix is: \n")
cm

The confucion matrix is: 



array([[1211,   87],
       [ 101, 1039]], dtype=int64)

In [14]:
print("The accuracy of the model is: \n")
accuracy_score(y_test,y_pred)

The accuracy of the model is: 



0.9228876127973749

## 2. Fitting Bernoulli Naive Bayes to Training Set  

In [15]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train,y_train)

BernoulliNB()

## Prediction of the test set result: 

In [16]:
y_pred = classifier.predict(X_test)

## Checking confusion matrix and accuracy

In [17]:
from sklearn.metrics import confusion_matrix,accuracy_score

cm=confusion_matrix(y_test,y_pred)
print("The confucion matrix is: \n")
cm

The confucion matrix is: 



array([[1227,   71],
       [ 295,  845]], dtype=int64)

In [18]:
print("The accuracy of the model is: \n")
accuracy_score(y_test,y_pred)

The accuracy of the model is: 



0.8498769483182936

In [19]:
## Bernoulli Naive Bayes have lesser accuracy than gaussian

##  3. Fitting Multinomial Naive Bayes to Training Set

In [20]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train,y_train)

MultinomialNB()

## Prediction of the test set result:

In [21]:
y_pred = classifier.predict(X_test)

## Checking confusion matrix and accuracy

In [22]:
from sklearn.metrics import confusion_matrix,accuracy_score

cm=confusion_matrix(y_test,y_pred)
print("The confucion matrix is: \n")
cm

The confucion matrix is: 



array([[1218,   80],
       [ 378,  762]], dtype=int64)

In [23]:
print("The accuracy of the model is: \n")
accuracy_score(y_test,y_pred)

The accuracy of the model is: 



0.8121410992616899

In [24]:
## Mulinomial Naive Bayes have least accuracy.

# Other Supervised Machine Learning models 

### Logistic Regression 

In [25]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)
print("Accuracy: ", accuracy_score(y_test, y_pred))

Accuracy:  0.9520098441345365


C:\Users\Amal\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


### K - Nearest Neighbour model

In [26]:
#Making Machine learning model based on KNN

from sklearn.neighbors import KNeighborsClassifier

knnClassifier = KNeighborsClassifier(n_neighbors=5)

knnClassifier.fit(X_train, y_train)

y_pred = knnClassifier.predict(X_test)

In [27]:
#Checking accuracy of the model

from sklearn.metrics import accuracy_score

print("Accuracy: ", accuracy_score(y_test, y_pred))

Accuracy:  0.9983593109105825


## Distribution Tree model

### Gini Index 

In [28]:
#Distribution tree using GiniIndex criteria 

from sklearn.tree import DecisionTreeClassifier

clf_gini = DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=3, min_samples_leaf=5)
clf_gini.fit(X_train, y_train)

y_pred = clf_gini.predict(X_test)

print("Accuracy: ", accuracy_score(y_test, y_pred))

Accuracy:  0.9544708777686628


### Entropy 

In [29]:
clf_entropy = DecisionTreeClassifier(criterion = "entropy", random_state = 100,max_depth = 3, min_samples_leaf = 5)
clf_entropy.fit(X_train, y_train)

y_pred = clf_entropy.predict(X_test)

print("Accuracy: ", accuracy_score(y_test, y_pred))

Accuracy:  0.955701394585726


## Random Forest Classifier

In [30]:
from sklearn.ensemble import RandomForestClassifier

RFclf = RandomForestClassifier() 
 
RFclf.fit(X_train, y_train)
 
y_pred = RFclf.predict(X_test)
print("Accuracy: ", accuracy_score(y_test, y_pred))

Accuracy:  1.0


## SVM model 

In [31]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf', random_state = 1)
classifier.fit(X_train,y_train)

y_pred = classifier.predict(X_test)

In [32]:
cm = confusion_matrix(y_test,y_pred)
accuracy = float(cm.diagonal().sum())/len(y_test)
print("\nAccuracy Of SVM For The Given Dataset : ", accuracy)


Accuracy Of SVM For The Given Dataset :  0.9872846595570139


## INSIGHTS 

### 1) Among probablistic machine learning model, Gaussian Naive Bayes gave maximum accuracy

### 2) Out of all machine learning models, Random Forest classifier game maximum accuracy